### ISSUE TITLE
error while starting app with plugin installed

### ISSUE THREAD

**Issue by ontwikkelfabriek** [JouriFledderman/cordova-plugin-debuggable-webview#2]
> 02-25 16:42:10.072 8860-8860/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: nl.of.beeapp, PID: 8860
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{nl.of.beeapp/nl.of.beeapp.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Bundle.getBoolean(java.lang.String)' on a null object reference
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2339)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:155)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Bundle.getBoolean(java.lang.String)' on a null object reference
                                                     at com.jourif.debuggable.WebViewDebug.initialize(WebViewDebug.java:38)
    
-followed the install instructions , config.xml  settings ect.
-same result with android 5.1 and 9.0

**Comment by JouriFledderman** [comment]
Hi Ontwikkelfabriek,

Are you using the plugin inside a cordova project or an Android project? From the error it seems to me that you are using it inside an android project. Haven’t tried that before... It should work, but probably a bit different. You can try to add the WebViewDebug property that I add in the documentation to the config.xml to the manifest file straight away (since cordova generates the manifest file from the config.xml). The error suggest that the WebViewDebug property is not properly set in your manifest file.

Have some time later this week to dive a bit deeper into the problem, but that would be my starting point.

**Comment by ontwikkelfabriek** [comment]
It's a cordova, project.  I could not get it to work with direct injecting in the Manifest file. But it could be my project setup is wrong

**Comment by JouriFledderman** [comment]
Can you post some more information about your project, because then I might be able to help you debug. Information such as: 
- cordova and cordova-android versions
- code snippet from the config.xml
- code snippet from the resulting androidmanifest.xml

**Comment by ontwikkelfabriek** [comment]
I fixed it already for my needs. Thanx for the help.

**Comment by JouriFledderman** [comment]
Ok, good to hear! What did you need to do to fix it? And also, do you still think it is an issue from my side of the code. Because if that is the case, I would really like to know it so I can do something about it, so others do not have the same issue.

**Comment by JouriFledderman** [comment]
I am going to coose this issue since the problem was resolved. Because no clear reproduction or fix path was available, I can only assume there was no problem with the plugin itself.
